version: 0.0.{build}-{branch}

os: Visual Studio 2017

environment:
  QTDIR: C:\Qt\5.9\msvc2017_64

skip_commits:
  files:
    - docs/*
    - LICENSE.txt
    - README.md
    - AUTHORS.txt

pull_requests:
  do_not_increment_build_number: true

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: ers.bat setup

configuration:
  - Release

before_build:
  - cmd: ers.bat lint --all
  - set PATH=%PATH%;%QTDIR%

build_script:
  - cmd: ers.bat build --config Release
  - cmd: python ecu.py pack

artifacts:
  - path: build/*.zip
  - path: build/*.exe
    
deploy:
  - provider: Environment
    name: production
    release: ecu-$(appveyor_repo_branch)-$(appveyor_repo_commit)-v$(appveyor_build_version)
    artifact: build/*.exe
    on:
      branch: master
      appveyor_repo_tag: true
