version: 0.0.{build}-{branch}

os: Visual Studio 2017

environment:
  QTDIR: C:\Qt\5.9\msvc2017_64

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: ers.bat setup

configuration:
  - Release

before_build:
  - set PATH=%PATH%;%QTDIR%

build_script:
  - cmd: ers.bat build --config Release
  - cmd: python ecu.py pack

artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)/build/ecu-$(ECU_META_VERSION).zip
  - path: $(APPVEYOR_BUILD_FOLDER)/build/ecu-$(ECU_META_VERSION).exe
    
deploy:
  - provider: Environment
    name: production
    release: ecu-$(appveyor_repo_branch)-$(appveyor_repo_commit)-v$(appveyor_build_version)
    artifact: $(APPVEYOR_BUILD_FOLDER)/build/ecu-$(ECU_META_VERSION).exe
    on:
      branch: master
      appveyor_repo_tag: true
