version: 0.0.{build}-{branch}

os: Visual Studio 2017

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: set PATH=C:\Python36-x64;%PATH%
  - cmd: ers.bat setup

configuration:
  - Release

build_script:
  - cmd: ers.bat build --config Release

after_build: >-
  7z a ecu-%appveyor_repo_branch%-%appveyor_repo_commit%.zip LICENSE.txt
  %APPVEYOR_BUILD_FOLDER%\build\Release\ECU.exe
  %APPVEYOR_BUILD_FOLDER%\build\Release\ECU.pdb
  %APPVEYOR_BUILD_FOLDER%\frontends\reactjs\build
  %APPVEYOR_BUILD_FOLDER%\build\Release\vJoyInterface.dll
  %APPVEYOR_BUILD_FOLDER%\build\Release\atlas.dll
  
  && 7z rn ecu-%appveyor_repo_branch%-%appveyor_repo_commit%.zip build reactjs

artifacts:
  - path: ecu-$(appveyor_repo_branch)-$(appveyor_repo_commit).zip
    
deploy:
  - provider: Environment
    name: production
    release: ecu-$(appveyor_repo_branch)-$(appveyor_repo_commit)-v$(appveyor_build_version)
    artifact: ecu-$(appveyor_repo_branch)-$(appveyor_repo_commit).zip
    on:
      branch: master
      appveyor_repo_tag: true
