group("src")
project("ECU-hid-g27")
  uuid("ba460252-4f1d-11e7-b114-b2f933d5fe66")
  kind("StaticLib")
  language("C++")
  links({
    "ECU-hid",
    "Setupapi",
    "Hid",
  })
  files({
    "generic_input_driver.h",
    "generic_input_driver.cc",
    "generic_hid.h",
    "generic_hid.cc",
    })