group("src")
project("ECU-ui")
  uuid("2dad4414-2ece-11e7-93ae-92361f002671")
  kind("StaticLib")
  language("C++")
  files({
    "window.h",
    "window.cc",
    "ui_event.h",
    "menu_item.h",
    "menu_item.cc",
    "loop.h",
    "loop.cc",
    "window_listener.h",
    })