group("src")
project("ECU-graphics")
  uuid("27ad9235-df81-4095-a555-aa01e2ca094f")
  kind("StaticLib")
  language("C++")
  files({
    "app.cc",
    "app.h",
    "app_handler.cc",
    "app_handler.h",
    "app_handler_win.cc",
  })
  links({
    "libcef",
  })
