group("src")
project("ECU-hid")
  uuid("d4118174-efd3-433c-9ac2-237a4275aa69")
  kind("StaticLib")
  language("C++")
  files({
    "input_system.h",
    "input_system.cc",
    "input_driver.h",
    "input_driver.cc",
    "input_command.h",
    "input_command.cc",
    "console_commands.h",
  })